services:
  db:
    image: postgres:15-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: dev_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.15.2
    volumes:
      - ./db/migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database=postgres://dev_user:dev_password@db:5432/dev_db?sslmode=disable"
    depends_on:
      - db
    networks:
      - weather_net

volumes:
  postgres_data:

networks:
  weather_net:
    driver: bridge